### ISSUE TITLE
{"error": "res is not iterable"}

### ISSUE THREAD

**Issue by zamacona** [sanchezcarlosjr/arsus#1]
Hola, antes que nada muchas gracias por esta API. La eh estado usando por un tiempo y el día de hoy tuve problemas con una CURP, tarda mucho tiempo en responder y al final solo regresa el siguiente JSON:

 `{"error": "res is not iterable"}`

Si gustas enviarme un correo para que te envíe la CURP de manera privada.

cezamacona@gmail.com

**Comment by sanchezcarlosjr** [comment]
Hola Zamacona. La API no funciona por fallas en mi proveedor. Estoy buscando alternativas. Y agregar el resto de las funcionalidades.

**Comment by zamacona** [comment]
Muchas gracias!

**Comment by jlalfonso21** [comment]
Alguna actualizacion?
